strictness: medium
autodetect: yes

pylint:
  disable:
    # W0612: Unused variable %r
    - W0612
    # W0613: Unused argument %r
    - W0613
    # W0105: String statement has no effect
    - W0105
    # W0702: No exception type(s) specified
    - W0702
    # W0622: Redefining built-in variable
    - W0622
    # E1004: Missing argument to super()
    - E1004
    - E0001
    # W0212: 	Access to a protected member _cancelled of a client class
    - W0212

pyflakes:
  disable:
    # F401: unused import
    - F401
    # F841: local variable is assigned to but never used
    - F841